### ISSUE TITLE
Formatting of inline code in /doc/html

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/datatracker#4909]
### Describe the issue

https://datatracker.ietf.org/doc/html/rfc9180 includes a lot of inline code blocks (like [this one in Section 5.1.1](https://datatracker.ietf.org/doc/html/rfc9180#section-5.1.1)).  These render with two problems:

1. The default 3 character left gutter doesn't appear.
2. The pilcrow is rendered on a new line, which effectively leaves a three-line space between the code and subsequent text.

I spent a fair bit of time fixing this in the original code, so I'm surprised to see this not working.  

This is the version on DT:
![image](https://user-images.githubusercontent.com/67641/208000183-366fbfbf-fb8a-4c24-97d8-e5da3d2139fb.png)

This is the version produced with the code below:
![image](https://user-images.githubusercontent.com/67641/208000314-f14bc342-e790-4e77-a972-3e82702fa7d8.png)

The corrected version is basically indistinguishable from the text rendering.

<details>
<summary>I haven't done a full analysis, but here are the relevant CSS rules that appear to be missing:</summary>

```css
div:is(.artwork, .sourcecode) {
  display: flex;
  flex-wrap: nowrap;
  align-items: end;
}
div:is(.artwork, .sourcecode).alignCenter {
  justify-content: center;
}
div:is(.artwork, .sourcecode).alignRight {
  justify-content: end;
}
div:is(.artwork, .sourcecode)::before {
  flex: 0 1 3ch;
  content: "";
}
div:is(.artwork, .sourcecode).alignRight::before {
  flex-grow: 1;
}
div:is(.artwork, .sourcecode) pre {
  flex: 0 0 content;
  margin: 0;
  max-width: 72ch;
  overflow: auto;
}
div:is(.artwork, .sourcecode) .pilcrow {
  flex: 0 0 1ch;
}
```

This is non-trivial code, but the effect is to put the gutter, the figure, and the pilcrow into a horizontal flexbox.  Depending on alignment, this uses different rules for flex-grow on each.  This works out really nicely in my testing, and [should be supported by WeasyPrint](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#css-flexible-box-layout-module-level-1).

</details>

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
